include: /build/gitlab-ci.yml

# Skip deploy phase
stages:
    - dependencies
    - build
    - check

variables:
    LLVM_VERSION: "3.9.1"
    PROJECT_PATH: "sosy-lab/software/java-common-lib"
    GH_REF: "github.com/sosy-lab/llvm-j"


download-lib:
    <<: *cache_pull
    stage: build
    script: "ant -verbose download-library -Dllvm.version=$LLVM_VERSION"
    artifacts:
        paths:
            - lib/native


# Run unit tests without coverage and with dependency on download-lib
unit-tests:jdk-8:
  <<: *unit-tests
  script: "ant $ANT_PROPS_TEST -verbose unit-tests"
  dependencies:
    - build-dependencies
    - build:jdk-8
    - download-lib

unit-tests:jdk-9:
  <<: *unit-tests
  script: "ant $ANT_PROPS_TEST -verbose unit-tests"
  dependencies:
    - build-dependencies
    - build:jdk-9
    - download-lib
