include: /build/gitlab-ci.yml

variables:
  LLVM_VERSION: "3.9.1"
  PROJECT_PATH: "sosy-lab/software/llvm-j"
  GH_REF: "github.com/sosy-lab/llvm-j"

download-lib:
  stage: dependencies
  script: "ant -verbose download-library -Dllvm.version=$LLVM_VERSION"
  artifacts:
    paths:
      - lib/native

build:jdk-10:
    allow_failure: true

# Run unit tests without coverage and with dependency on download-lib
unit-tests:jdk-8:
  script: "ant $ANT_PROPS_TEST -verbose unit-tests"
  dependencies:
    - build-dependencies
    - build:jdk-8
    - download-lib

unit-tests:jdk-9:
  script: "ant $ANT_PROPS_TEST -verbose unit-tests"
  dependencies:
    - build-dependencies
    - build:jdk-9
    - download-lib

unit-tests:jdk-10:
  script: "ant $ANT_PROPS_TEST -verbose unit-tests"
  allow_failure: true
  dependencies:
    - build-dependencies
    - build:jdk-10
    - download-lib

bindings-build:
  # Put in stage 'checks' to make other checks not dependent on its failure
  stage: checks
  dependencies:
    - build-dependencies
  script:
    - "ant bindings -Dllvm.home=/usr/include/llvm-c-3.9/llvm-c"
    - "git diff --exit-code"
